In [1]:
import numpy as np
A = np.array([0.2, 0.5, 0.7])
B = np.array([0.3, 0.6, 0.8])
# Basic operations
print("Union:", np.maximum(A,B))
print("Intersection:", np.minimum(A,B))
print("Complement A:", 1-A)
print("Difference A-B:", np.minimum(A,1-B))
# Fuzzy relations (Cartesian product using min)
R = np.minimum.outer(A,B)
S = np.minimum.outer(B,A)
# Max-Min Composition
comp = np.array([[max(min(R[i][k], S[k][j]) for k in range(len(B))) for j in range(len(A))] for i in range(len(A))])
print("Relation R:\n", R)
print("Relation S:\n", S)
print("Max-Min Composition:\n", comp)

Union: [0.3 0.6 0.8]
Intersection: [0.2 0.5 0.7]
Complement A: [0.8 0.5 0.3]
Difference A-B: [0.2 0.4 0.2]
Relation R:
 [[0.2 0.2 0.2]
 [0.3 0.5 0.5]
 [0.3 0.6 0.7]]
Relation S:
 [[0.2 0.3 0.3]
 [0.2 0.5 0.6]
 [0.2 0.5 0.7]]
Max-Min Composition:
 [[0.2 0.2 0.2]
 [0.2 0.5 0.5]
 [0.2 0.5 0.7]]
